# Reusable workflow that expects secrets to be passed explicitly

name: Reusable Workflow - Explicit Secrets Demo

on:
  workflow_call:
    inputs:
      username:
        description: 'The username to greet'
        required: false
        type: string
        default: 'User'
    secrets:
      # This reusable workflow declares that it expects a secret named 'EXPECTED_SECRET_NAME'.
      # The caller must provide this secret.
      EXPECTED_SECRET_NAME:
        description: 'A secret that is explicitly passed by the caller workflow.'
        required: true

jobs:
  use-explicitly-passed-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Greet User
        run: echo "Hello, ${{ inputs.username }}!"

      - name: Access the explicitly passed secret
        run: |
          if [ -n "${{ secrets.EXPECTED_SECRET_NAME }}" ]; then
            echo "Successfully accessed the explicitly passed secret (EXPECTED_SECRET_NAME)."
            # You can use the secret here, for example:
            # echo "Secret value starts with: $(echo ${{ secrets.EXPECTED_SECRET_NAME }} | cut -c 1-3)..."
          else
            echo "Error: The explicitly passed secret (EXPECTED_SECRET_NAME) was not received."
            exit 1
          fi
